export const ADD_PROJECT = 'PROJECTS/ADD_PROJECT';
export const DELETE_PROJECT = 'PROJECTS/DELETE_PROJECT';
export const HIDE_LOADER = 'PROJECTS/HIDE_LOADER';
export const SHOW_LOADER = 'PROJECTS/SHOW_LOADER';
export const FETCH_PROJECTS_SUCCESS = 'PROJECTS/FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'PROJECTS/FETCH_PROJECTS_FAILURE';
export const UPDATE_PROJECT = 'PROJECTS/UPDATE_PROJECT';
export const SHOW_ERROR = 'PROJECTS/SHOW_ERROR';
