export const HIDE_EDIT = 'TASK_LIST/HIDE_EDIT';
export const SHOW_EDIT = 'TASK_LIST/SHOW_EDIT';
export const SELECT_TASK = 'TASK_LIST/SELECT_TASK';
export const DESELECT_TASK = 'TASK_LIST/DESELECT_TASK';
