export const ADD = 'TASK/ADD';
export const ADD_FAILURE = 'TASK/ADD_FAILURE';
export const FETCH_TASKS = 'TASK/FETCH_TASKS';
export const FETCH_TASKS_FAILURE = 'TASK/FETCH_TASKS_FAILURE';
export const REMOVE = 'TASK/REMOVE';
export const REMOVE_FAILURE = 'TASK/REMOVE_FAILURE';
export const UPDATE = 'TASK/UPDATE';
export const UPDATE_FAILURE = 'TASK/UPDATE_FAILURE';
