export const ADD = 'TASK/ADD';
export const ADD_FAILURE = 'TASK/ADD_FAILURE';
export const FETCH_TASKS = 'TASK/FETCH_TASKS';
export const FETCH_TASKS_FAILURE = 'TASK/FETCH_TASKS_FAILURE';
export const REMOVE_TASK = 'TASK/REMOVE';
export const UPDATE = 'TASK/UPDATE';
export const UPDATE_FAILURE = 'TASK/UPDATE_FAILURE';

export const SET_NEW_TASK_TITLE = 'TASK/SET_NEW_TITLE';
